db_hw_4_4/accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

db_hw_4_4/book_review_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('libraries/', include('libraries.urls')),
    path('accounts/',include('accounts.urls')),
]

db_hw_4_4/libraries/urls.py
from django.urls import path
from . import views


app_name = 'libraries'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:book_pk>/', views.detail, name='detail'),
    path('<int:pk>/review/', views.review, name='review'),
    path('<int:book_pk>/reviews/<int:review_pk>/delete/',
         views.review_delete, name='review_delete'),
]

db_hw_4_4/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

db_hw_4_4/libraries/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=200)

class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    content = models.CharField(max_length=250)

db_hw_4_4/libraries/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('content', )

db_hw_4_4/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

# Create your views here.
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('libraries:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('accounts:login')

db_hw_4_4/libraries/views.py
from django.shortcuts import render, redirect
from .models import Book, Review

from .forms import ReviewForm
# Create your views here.
def index(request):
    books = Book.objects.all()
    context = {
        'books': books
    }
    return render(request, 'libraries/index.html', context)

def detail(request, book_pk):
    book = Book.objects.get(pk=book_pk)
    reviewForm = ReviewForm()
    reviews = book.review_set.all()
    context = {
        'book': book,
        'reviewForm' : reviewForm,
        'reviews' : reviews,
    }
    return render(request, 'libraries/detail.html', context)

def review(request, pk):
    book = Book.objects.get(pk=pk)
    reviewForm = ReviewForm(request.POST)
    if reviewForm.is_valid():
        review =reviewForm.save(commit=False)
        review.book = book
        review.user = request.user
        review.save()
        return redirect('libraries:detail' , book.pk)
    context = {
        'book' : book,
        'reviewForm' : reviewForm,
    }
    return render(request, 'libraries/detail.html', context)

def review_delete(request, book_pk, review_pk):
    review = Review.objects.get(pk = review_pk)
    if request.user == review.user:
        book = Book.objects.get(pk = book_pk)
        review.delete()
    return redirect('libraries:detail', book_pk)

db_hw_4_4/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
  <h1>로그인 페이지</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="로그인">
  </form>
{% endblock content %}

db_hw_4_4/libraries/templates/libraries/detail.html
{% extends 'base.html' %}

{% block content %}
  {% if request.user.is_authenticated %}
  <p>안녕하세요 {{ user.username }}</p>
  <form action="{% url "accounts:logout" %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="LOGOUT">
  </form>
  {% else %}
    <a href="{% url "accounts:login" %}">LOGIN</a>
  {% endif %}

  <h1>책 상세 정보</h1>
  <p>등록 번호 : {{ book.pk }}</p>
  <p>제목 : {{ book.title }}</p>
  <p>설명 : {{ book.description }}</p>
  <hr>

  <h3>리뷰 등록</h3>
  {% if request.user.is_authenticated %}
  <form action="{% url "libraries:review" book.pk %}" method = 'POST'>
    {% csrf_token %}
    {{reviewForm.as_p}}
    <input type="submit" value="리뷰 작성">
  </form>
  {% else %}
  <p>로그인 후 작성해주세요.</p>
  {% endif %}
  
  <hr>

  <h3> 리뷰 전체 목록 </h3>
  <ul>
    {% for review in reviews %}
      <li>
        <p>
          {{review.user.username}} | {{review.content}}
        </p>
        {% if request.user == review.user %}
          <form action="{% url "libraries:review_delete" book.pk review.pk %}" method = 'POST'>
            {% csrf_token %}
            <input type="submit" value='삭제'>
          </form>
        {% endif %}
      </li>
    {% endfor %}
  </ul>


  <a href="{% url "libraries:index" %}">[BACK]</a>
{% endblock content %}

db_hw_4_4/libraries/templates/libraries/index.html
{% extends 'base.html' %}

{% block content %}
{% if request.user.is_authenticated %}
<p>안녕하세요 {{ user.username }}</p>
<form action="{% url "accounts:logout" %}" method="POST">
  {% csrf_token %}
  <input type="submit" value="LOGOUT">
</form>
{% else %}
  <a href="{% url "accounts:login" %}">LOGIN</a>
{% endif %}


  <h1>책 전체 목록</h1>
  <ul>
    {% for book in books %}
      <a href="{% url 'libraries:detail' book.pk %}">
        <li>제목 : {{ book.title }}</li>
      </a>
      <hr>
    {% endfor %}
  </ul>
{% endblock content %}

db_hw_4_4/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  {% block content %}

  {% endblock content %}
</body>
</html>